// Generated by https://quicktype.io

export interface Products {
  current_page: number
  data: Datum[]
  first_page_url: string
  from: number
  last_page: number
  last_page_url: string
  links: Link[]
  next_page_url: string
  path: string
  per_page: number
  prev_page_url: null
  to: number
  total: number
}

export interface Datum {
  category_uuid?: string
  title?: string
  uuid?: string
  price?: number
  description?: string
  metadata?: Metadata
  created_at?: string
  updated_at?: string
  deleted_at?: null
  category?: Brand
  brand?: Brand
  content?: string
  slug?: string
}

export interface Brand {
  uuid?: string
  title?: string
  slug?: string
  created_at?: string
  updated_at?: string
}

export interface Metadata {
  brand?: string
  image?: string
  valid_from?: string
  valid_to?: string
}

export interface Link {
  url?: null | string
  label?: string
  active?: boolean
}
